### ISSUE TITLE
Hack The Web

### ISSUE THREAD

**Issue by virus-rpi** [BaumianerNiklas/site#1]
Hast du bei der Hack the Web Aufgabe „Orakel“ auch das Lösungswort erraten oder einen Botgeschrieben, der immer mal wieder nachguckt?

**Comment by BaumianerNiklas** [comment]
Hab's erraten, haha. Das Lösungswort war so ziemlich das erste was mir zu "Orakel" eingefallen ist

**Comment by BaumianerNiklas** [comment]
Hey, hatte grad ne nette Idee und wollte fragen, ob ihr Lust auf einen Hack the Web Discord Server hättet? Dann müssten wir nicht immer auf GitHub Issues ausweichen, wenn wir uns irgendwas zu sagen haben und ich glaube, das würde ne angenehme Runde werden, da wir ja denke ich alle einigermaßen gleichgesinnt sind :) Ich weiß nicht, ob ihr Discord benutzt, aber wenn ihr Lust auf sowas hättet, wäre ich gern dazu bereit den Server zu erstellen

**Comment by virus-rpi** [comment]
Das ist eine sehr gute Idee. Willst du den erstellen oder soll ich das machen?

**Comment by BaumianerNiklas** [comment]
Hab jetzt einfach mal einen erstellt: https://discord.gg/9zDMZP9edd
